-- PostgreSQL 17. New empty PUBLIC schema only.
CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;
-- PostgreSQL enums extracted from frozen V1.1 Prisma reference
CREATE TYPE public."RequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE public."UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');
CREATE TYPE public."AffiliateStatus" AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE public."IdentificationType" AS ENUM ('NATIONAL', 'DIMEX');
CREATE TYPE public."GovernanceTermStatus" AS ENUM ('PLANNED', 'ACTIVE', 'CLOSED', 'CANCELLED');
CREATE TYPE public."AssemblyType" AS ENUM ('ORDINARY', 'EXTRAORDINARY');
CREATE TYPE public."AssemblyStatus" AS ENUM ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');
CREATE TYPE public."AssemblyQuorumType" AS ENUM ('FIXED', 'PERCENTAGE');
CREATE TYPE public."AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'JUSTIFIED');
CREATE TYPE public."JustificationStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE public."SanctionStatus" AS ENUM ('ACTIVE', 'RESOLVED', 'REVOKED');
CREATE TYPE public."EventStatus" AS ENUM ('SCHEDULED', 'CANCELLED', 'COMPLETED');
CREATE TYPE public."PublicationStatus" AS ENUM ('INTERNAL', 'DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE public."ReservableResourceStatus" AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE public."ResourcePricingType" AS ENUM ('FREE', 'FIXED');
CREATE TYPE public."ReservationStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'CONFIRMED', 'COMPLETED');
CREATE TYPE public."FinancialChargeStatus" AS ENUM ('PENDING', 'PAID', 'CANCELLED');
CREATE TYPE public."PaymentStatus" AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED');
CREATE TYPE public."PaymentMethod" AS ENUM ('CASH', 'BANK_TRANSFER', 'SINPE_MOVIL', 'OTHER');
CREATE TYPE public."DonationStatus" AS ENUM ('CONFIRMED', 'CANCELLED');
CREATE TYPE public."DonationMethod" AS ENUM ('CASH', 'BANK_TRANSFER', 'SINPE_MOVIL', 'OTHER');
CREATE TYPE public."FinancialMethod" AS ENUM ('CASH', 'BANK_TRANSFER', 'SINPE_MOVIL', 'CHECK', 'OTHER');
CREATE TYPE public."FinancialMovementType" AS ENUM ('INCOME', 'EXPENSE');
CREATE TYPE public."FinancialMovementSource" AS ENUM ('MANUAL', 'RESERVATION_PAYMENT', 'DONATION');
CREATE TYPE public."FinancialMovementOriginType" AS ENUM ('MANUAL', 'PAYMENT', 'DONATION', 'DISBURSEMENT');
CREATE TYPE public."FinancialMovementStatus" AS ENUM ('POSTED', 'VOIDED');
CREATE TYPE public."ExpenseStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
CREATE TYPE public."FundingSourceType" AS ENUM ('FONDO_POR_GIRAR', 'IMPUESTO_CEMENTO', 'OWN_FUNDS', 'OTHER');
CREATE TYPE public."InventoryItemStatus" AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE public."InventoryItemCondition" AS ENUM ('GOOD', 'DAMAGED', 'UNDER_REPAIR');
CREATE TYPE public."InventoryMovementType" AS ENUM ('OPENING_BALANCE', 'ENTRY', 'EXIT', 'ADJUSTMENT');
CREATE TYPE public."InventoryLoanStatus" AS ENUM ('ACTIVE', 'RETURNED', 'CANCELLED');
CREATE TYPE public."InstitutionalOrganizationType" AS ENUM ('INTEGRAL', 'SPECIFIC');
CREATE TYPE public."BoardPosition" AS ENUM ('PRESIDENT', 'VICE_PRESIDENT', 'SECRETARY', 'TREASURER', 'VOCAL', 'FISCAL', 'SUPLENTE');
CREATE TYPE public."VolunteerOpportunityStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'CLOSED', 'COMPLETED', 'CANCELLED');
CREATE TYPE public."VolunteerSessionStatus" AS ENUM ('SCHEDULED', 'COMPLETED', 'CANCELLED');
CREATE TYPE public."VolunteerApplicationStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN');
CREATE TYPE public."VolunteerParticipationStatus" AS ENUM ('CONFIRMED', 'COMPLETED', 'CANCELLED');
CREATE TYPE public."VolunteerAttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'EXCUSED');
CREATE TYPE public."VentureStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'CLOSED');
CREATE TYPE public."VenturePublicationStatus" AS ENUM ('UNPUBLISHED', 'PUBLISHED');
CREATE TYPE public."VentureRequestPurpose" AS ENUM ('REGISTRATION', 'UPDATE');
CREATE TYPE public."VentureRequestStatus" AS ENUM ('SUBMITTED', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'REJECTED', 'WITHDRAWN');
CREATE TYPE public."MaintenanceWorkOrderStatus" AS ENUM ('DRAFT', 'AUTHORIZED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'CLOSED', 'CANCELLED');
CREATE TYPE public."DisbursementPurpose" AS ENUM ('REGULAR', 'ADVANCE', 'SETTLEMENT');
CREATE TYPE public."ExpenseType" AS ENUM ('OPERATING', 'MAINTENANCE', 'EXTRAORDINARY');
