-- 82 authoritative dictionary tables (excludes conditional OD-01).
CREATE TABLE public."InstitutionalProfile" (
  "id" integer NOT NULL DEFAULT 1,
  "legalName" text,
  "legalIdentification" text,
  "dinadecoRegistrationCode" text,
  "dinadecoRegion" text,
  "organizationType" "InstitutionalOrganizationType",
  "province" text,
  "canton" text,
  "district" text,
  "locality" text,
  "correspondenceAddress" text,
  "phone" text,
  "telefax" text,
  "email" text,
  "canonicalLegalName" varchar(200),
  "canonicalLegalIdentification" varchar(64),
  "canonicalDinadecoRegistrationCode" varchar(64),
  "canonicalOrganizationType" varchar(100),
  "canonicalRegion" varchar(100),
  "canonicalProvince" varchar(100),
  "canonicalCanton" varchar(100),
  "canonicalDistrict" varchar(100),
  "canonicalPhysicalAddress" varchar(500),
  "canonicalNotificationPhone" varchar(40),
  "canonicalNotificationFax" varchar(40),
  "canonicalNotificationEmail" varchar(254),
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_InstitutionalProfile" PRIMARY KEY ("id")
);

CREATE TABLE public."Person" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "firstName" text,
  "firstSurname" text,
  "secondSurname" text,
  "legacyFullName" text,
  "identification" text,
  "identificationType" "IdentificationType",
  "normalizedIdentification" text,
  "birthDate" timestamp(3) without time zone,
  "email" text,
  "phoneCountryCode" text,
  "phoneNationalNumber" text,
  "address" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_Person" PRIMARY KEY ("id")
);

CREATE TABLE public."Role" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_Role" PRIMARY KEY ("id")
);

CREATE TABLE public."Permission" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_Permission" PRIMARY KEY ("id")
);

CREATE TABLE public."RolePermission" (
  "roleId" integer NOT NULL,
  "permissionId" integer NOT NULL,
  CONSTRAINT "pk_RolePermission" PRIMARY KEY ("roleId", "permissionId")
);

CREATE TABLE public."User" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "fullName" text NOT NULL,
  "identification" text NOT NULL,
  "email" text NOT NULL,
  "phone" text,
  "address" text,
  "passwordHash" text,
  "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
  "failedLoginAttempts" integer NOT NULL DEFAULT 0,
  "lockedAt" timestamp(3) without time zone,
  "lastLoginAt" timestamp(3) without time zone,
  "personId" integer NOT NULL,
  "identificationType" "IdentificationType",
  "phoneCountryCode" text,
  "phoneNationalNumber" text,
  "subscriptionExpirationDate" timestamp(3) without time zone,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_User" PRIMARY KEY ("id")
);

CREATE TABLE public."Session" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "refreshTokenHash" text NOT NULL,
  "expiresAt" timestamp(3) without time zone NOT NULL,
  "revokedAt" timestamp(3) without time zone,
  "revocationReason" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "userId" integer NOT NULL,
  CONSTRAINT "pk_Session" PRIMARY KEY ("id")
);

CREATE TABLE public."AuditLog" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "action" text NOT NULL,
  "module" text NOT NULL,
  "entityType" text,
  "entityId" text,
  "details" jsonb,
  "ipAddress" text,
  "userAgent" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "userId" integer,
  CONSTRAINT "pk_AuditLog" PRIMARY KEY ("id")
);

CREATE TABLE public."PasswordResetToken" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tokenHash" text NOT NULL,
  "expiresAt" timestamp(3) without time zone NOT NULL,
  "usedAt" timestamp(3) without time zone,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "userId" integer NOT NULL,
  CONSTRAINT "pk_PasswordResetToken" PRIMARY KEY ("id")
);

CREATE TABLE public."AccountActivationToken" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tokenHash" text NOT NULL,
  "expiresAt" timestamp(3) without time zone NOT NULL,
  "usedAt" timestamp(3) without time zone,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "userId" integer NOT NULL,
  CONSTRAINT "pk_AccountActivationToken" PRIMARY KEY ("id")
);

CREATE TABLE public."UserRequest" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "fullName" text NOT NULL,
  "identification" text NOT NULL,
  "email" text NOT NULL,
  "phone" text,
  "address" text,
  "reason" text NOT NULL,
  "status" "RequestStatus" NOT NULL DEFAULT 'PENDING',
  "rejectionReason" text,
  "reviewedAt" timestamp(3) without time zone,
  "reviewedById" integer,
  "identificationType" "IdentificationType",
  "phoneCountryCode" text,
  "phoneNationalNumber" text,
  "personId" integer,
  "submittedFullName" text,
  "submittedIdentification" text,
  "submittedIdentificationType" "IdentificationType",
  "submittedEmail" text,
  "submittedPhone" text,
  "submittedPhoneCountryCode" text,
  "submittedPhoneNationalNumber" text,
  "submittedAddress" text,
  "submittedReason" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_UserRequest" PRIMARY KEY ("id")
);

CREATE TABLE public."Affiliate" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "fullName" text NOT NULL,
  "identification" text NOT NULL,
  "birthDate" timestamp(3) without time zone NOT NULL,
  "gender" text,
  "phone" text,
  "email" text,
  "address" text NOT NULL,
  "occupation" text,
  "workplace" text,
  "affiliateType" text,
  "affiliationDate" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "status" "AffiliateStatus" NOT NULL DEFAULT 'ACTIVE',
  "identificationType" "IdentificationType",
  "phoneCountryCode" text,
  "phoneNationalNumber" text,
  "personId" integer,
  "roleId" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_Affiliate" PRIMARY KEY ("id")
);

CREATE TABLE public."AffiliateRequest" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "fullName" text NOT NULL,
  "identification" text NOT NULL,
  "birthDate" timestamp(3) without time zone NOT NULL,
  "gender" text,
  "phone" text,
  "email" text,
  "address" text NOT NULL,
  "occupation" text,
  "workplace" text,
  "affiliationReason" text NOT NULL,
  "status" "RequestStatus" NOT NULL DEFAULT 'PENDING',
  "rejectionReason" text,
  "reviewedAt" timestamp(3) without time zone,
  "reviewedById" integer,
  "identificationType" "IdentificationType",
  "phoneCountryCode" text,
  "phoneNationalNumber" text,
  "personId" integer,
  "submittedFullName" text,
  "submittedIdentification" text,
  "submittedIdentificationType" "IdentificationType",
  "submittedBirthDate" timestamp(3) without time zone,
  "submittedGender" text,
  "submittedPhone" text,
  "submittedPhoneCountryCode" text,
  "submittedPhoneNationalNumber" text,
  "submittedEmail" text,
  "submittedAddress" text,
  "submittedOccupation" text,
  "submittedWorkplace" text,
  "submittedAffiliationReason" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_AffiliateRequest" PRIMARY KEY ("id")
);

CREATE TABLE public."AffiliateSanction" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reason" text NOT NULL,
  "description" text,
  "date" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "status" "SanctionStatus" NOT NULL DEFAULT 'ACTIVE',
  "affiliateId" integer NOT NULL,
  "createdById" integer NOT NULL,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_AffiliateSanction" PRIMARY KEY ("id")
);

CREATE TABLE public."GovernancePosition" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_GovernancePosition" PRIMARY KEY ("id")
);

CREATE TABLE public."BoardTerm" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "institutionalProfileId" integer NOT NULL,
  "startsOn" date NOT NULL,
  "endsOn" date NOT NULL,
  "status" "GovernanceTermStatus",
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_BoardTerm" PRIMARY KEY ("id")
);

CREATE TABLE public."BoardAppointment" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "boardTermId" integer NOT NULL,
  "personId" integer NOT NULL,
  "position" "BoardPosition" NOT NULL,
  "positionId" integer,
  "affiliateId" integer,
  "seatNumber" integer,
  "startsOn" date,
  "endsOn" date,
  "appointedByAssemblyId" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_BoardAppointment" PRIMARY KEY ("id")
);

CREATE TABLE public."Assembly" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" text NOT NULL,
  "assemblyType" "AssemblyType",
  "type" text,
  "date" timestamp(3) without time zone NOT NULL,
  "scheduledAt" timestamp(3) without time zone,
  "heldAt" timestamp(3) without time zone,
  "place" text NOT NULL,
  "description" text,
  "status" "AssemblyStatus" NOT NULL DEFAULT 'SCHEDULED',
  "quorumType" "AssemblyQuorumType",
  "quorumValue" integer,
  "convocationsLockedAt" timestamp(3) without time zone,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_Assembly" PRIMARY KEY ("id")
);

CREATE TABLE public."AssemblyCall" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "assemblyId" integer NOT NULL,
  "callNumber" integer NOT NULL,
  "scheduledAt" timestamp(3) without time zone NOT NULL,
  "quorumType" "AssemblyQuorumType" NOT NULL,
  "quorumValue" integer NOT NULL,
  "startedAt" timestamp(3) without time zone,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_AssemblyCall" PRIMARY KEY ("id")
);

CREATE TABLE public."AssemblyConvocation" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "assemblyId" integer NOT NULL,
  "affiliateId" integer NOT NULL,
  "roleId" integer,
  "roleNameSnapshot" text NOT NULL,
  "governanceMembershipId" integer,
  "positionNameSnapshot" text,
  "convenedAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_AssemblyConvocation" PRIMARY KEY ("id")
);

CREATE TABLE public."AssemblyAttendance" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "status" "AttendanceStatus" NOT NULL,
  "registeredAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "observations" text,
  "assemblyId" integer NOT NULL,
  "affiliateId" integer NOT NULL,
  "convocationId" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_AssemblyAttendance" PRIMARY KEY ("id")
);

CREATE TABLE public."AbsenceJustification" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reason" text NOT NULL,
  "status" "JustificationStatus" NOT NULL DEFAULT 'PENDING',
  "rejectionReason" text,
  "reviewedAt" timestamp(3) without time zone,
  "assemblyId" integer NOT NULL,
  "affiliateId" integer NOT NULL,
  "attendanceId" integer,
  "reviewedById" integer,
  "decisionNote" text,
  "attachmentOriginalName" text,
  "attachmentMimeType" text,
  "attachmentSize" integer,
  "attachmentUrl" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_AbsenceJustification" PRIMARY KEY ("id")
);

CREATE TABLE public."AssemblyMinute" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "assemblyId" integer NOT NULL,
  "content" text NOT NULL,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_AssemblyMinute" PRIMARY KEY ("id")
);

CREATE TABLE public."AssemblyResolution" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "assemblyId" integer NOT NULL,
  "title" text NOT NULL,
  "content" text NOT NULL,
  "resolvedAt" timestamp(3) without time zone,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_AssemblyResolution" PRIMARY KEY ("id")
);

CREATE TABLE public."Event" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "publicId" text NOT NULL DEFAULT gen_random_uuid(),
  "title" text NOT NULL,
  "summary" text NOT NULL,
  "description" text,
  "startAt" timestamp(3) without time zone NOT NULL,
  "endAt" timestamp(3) without time zone,
  "location" text,
  "status" "EventStatus" NOT NULL DEFAULT 'SCHEDULED',
  "publicationStatus" "PublicationStatus" NOT NULL DEFAULT 'DRAFT',
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  "initiative_id" integer,
  CONSTRAINT "pk_Event" PRIMARY KEY ("id")
);

CREATE TABLE public."ReservableResource" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "location" text,
  "capacity" integer,
  "status" "ReservableResourceStatus" NOT NULL DEFAULT 'ACTIVE',
  "price" numeric(14,2),
  "currency" text NOT NULL DEFAULT 'CRC',
  "pricingType" "ResourcePricingType" NOT NULL DEFAULT 'FREE',
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  "facility_id" integer,
  CONSTRAINT "pk_ReservableResource" PRIMARY KEY ("id")
);

CREATE TABLE public."Reservation" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "startAt" timestamp(3) without time zone NOT NULL,
  "endAt" timestamp(3) without time zone NOT NULL,
  "purpose" text NOT NULL,
  "estimatedAttendees" integer,
  "notes" text,
  "status" "ReservationStatus" NOT NULL DEFAULT 'PENDING',
  "approvedAt" timestamp(3) without time zone,
  "rejectionReason" text,
  "cancelledAt" timestamp(3) without time zone,
  "resourceId" integer NOT NULL,
  "requesterUserId" integer NOT NULL,
  "approvedById" integer,
  "eventId" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_Reservation" PRIMARY KEY ("id")
);

CREATE TABLE public."FinancialAccount" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "currency" text NOT NULL DEFAULT 'CRC',
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_FinancialAccount" PRIMARY KEY ("id")
);

CREATE TABLE public."FinancialCharge" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reservationId" integer NOT NULL,
  "amount" numeric(14,2) NOT NULL,
  "currency" text NOT NULL DEFAULT 'CRC',
  "status" "FinancialChargeStatus" NOT NULL DEFAULT 'PENDING',
  "dueAt" timestamp(3) without time zone,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_FinancialCharge" PRIMARY KEY ("id")
);

CREATE TABLE public."Payment" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "chargeId" integer NOT NULL,
  "movementId" integer,
  "amount" numeric(14,2) NOT NULL,
  "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',
  "method" "PaymentMethod" NOT NULL,
  "financialMethod" "FinancialMethod",
  "reference" text,
  "paidAt" timestamp(3) without time zone,
  "recordedById" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_Payment" PRIMARY KEY ("id")
);

CREATE TABLE public."FinancialMovement" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "accountId" integer,
  "type" "FinancialMovementType" NOT NULL,
  "source" "FinancialMovementSource" NOT NULL DEFAULT 'MANUAL',
  "sourceId" integer,
  "originType" "FinancialMovementOriginType",
  "amount" numeric(14,2) NOT NULL,
  "currency" text NOT NULL DEFAULT 'CRC',
  "description" text NOT NULL,
  "reference" text,
  "occurredAt" timestamp(3) without time zone NOT NULL,
  "recordedById" integer,
  "status" "FinancialMovementStatus",
  "reversalOfId" integer,
  "voidedAt" timestamp(3) without time zone,
  "voidedById" integer,
  "voidReason" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  "initiative_id" integer,
  "destination_type" varchar(32),
  CONSTRAINT "pk_FinancialMovement" PRIMARY KEY ("id")
);

CREATE TABLE public."Donation" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "donorPersonId" integer,
  "donorName" text,
  "donorIdentification" text,
  "amount" numeric(14,2) NOT NULL,
  "currency" text NOT NULL DEFAULT 'CRC',
  "method" "DonationMethod" NOT NULL,
  "financialMethod" "FinancialMethod",
  "reference" text,
  "description" text,
  "receivedAt" timestamp(3) without time zone NOT NULL,
  "status" "DonationStatus" NOT NULL DEFAULT 'CONFIRMED',
  "recordedById" integer NOT NULL,
  "cancelledById" integer,
  "cancelledAt" timestamp(3) without time zone,
  "cancellationReason" text,
  "originalMovementId" integer,
  "reversalMovementId" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  "donor_id" integer,
  CONSTRAINT "pk_Donation" PRIMARY KEY ("id")
);

CREATE TABLE public."Expense" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "description" text NOT NULL,
  "amount" numeric(14,2) NOT NULL,
  "currency" text NOT NULL DEFAULT 'CRC',
  "incurredAt" timestamp(3) without time zone NOT NULL,
  "status" "ExpenseStatus" NOT NULL DEFAULT 'PENDING',
  "authorizationResolutionId" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  "maintenance_work_order_id" integer,
  "board_resolution_id" integer,
  "expense_type" varchar(32),
  "maintenance_cost_recognized_at" timestamp(3) without time zone,
  CONSTRAINT "pk_Expense" PRIMARY KEY ("id")
);

CREATE TABLE public."ExpenseDocument" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "expenseId" integer NOT NULL,
  "originalName" text NOT NULL,
  "mimeType" text NOT NULL,
  "size" integer NOT NULL,
  "url" text NOT NULL,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "document_version_id" integer,
  CONSTRAINT "pk_ExpenseDocument" PRIMARY KEY ("id")
);

CREATE TABLE public."Disbursement" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "expenseId" integer NOT NULL,
  "movementId" integer NOT NULL,
  "amount" numeric(14,2) NOT NULL,
  "currency" text NOT NULL DEFAULT 'CRC',
  "method" "FinancialMethod" NOT NULL,
  "reference" text,
  "paidAt" timestamp(3) without time zone NOT NULL,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  "purpose" varchar(32) NOT NULL DEFAULT 'REGULAR',
  "settled_at" timestamp(3) without time zone,
  "settled_by_user_id" integer,
  CONSTRAINT "pk_Disbursement" PRIMARY KEY ("id")
);

CREATE TABLE public."FundingAllocation" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "expenseId" integer NOT NULL,
  "sourceType" "FundingSourceType" NOT NULL,
  "amount" numeric(14,2) NOT NULL,
  "incomeMovementId" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_FundingAllocation" PRIMARY KEY ("id")
);

CREATE TABLE public."InventoryCategory" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_InventoryCategory" PRIMARY KEY ("id")
);

CREATE TABLE public."InventoryItem" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "currentQuantity" integer NOT NULL DEFAULT 0,
  "minimumQuantity" integer NOT NULL DEFAULT 0,
  "unit" text NOT NULL DEFAULT 'unidad',
  "location" text,
  "status" "InventoryItemStatus" NOT NULL DEFAULT 'ACTIVE',
  "condition" "InventoryItemCondition" NOT NULL DEFAULT 'GOOD',
  "categoryId" integer NOT NULL,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_InventoryItem" PRIMARY KEY ("id")
);

CREATE TABLE public."InventoryMovement" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" "InventoryMovementType" NOT NULL,
  "quantity" integer NOT NULL,
  "quantityDelta" integer,
  "reason" text NOT NULL,
  "reference" text,
  "notes" text,
  "itemId" integer NOT NULL,
  "createdById" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_InventoryMovement" PRIMARY KEY ("id")
);

CREATE TABLE public."InventoryLoan" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "quantity" integer NOT NULL,
  "borrowerName" text NOT NULL,
  "loanDate" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "expectedReturnDate" timestamp(3) without time zone NOT NULL,
  "returnedAt" timestamp(3) without time zone,
  "status" "InventoryLoanStatus" NOT NULL DEFAULT 'ACTIVE',
  "notes" text,
  "itemId" integer NOT NULL,
  "borrowerAffiliateId" integer,
  "createdById" integer,
  "receivedById" integer,
  "cancelledById" integer,
  "cancelledAt" timestamp(3) without time zone,
  "cancellationReason" text,
  "checkoutMovementId" integer,
  "returnMovementId" integer,
  "cancellationMovementId" integer,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_InventoryLoan" PRIMARY KEY ("id")
);

CREATE TABLE public."VolunteerOpportunity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "location" text,
  "capacity" integer,
  "applicationDeadline" timestamp(3) without time zone,
  "status" "VolunteerOpportunityStatus" NOT NULL DEFAULT 'DRAFT',
  "createdByUserId" integer NOT NULL,
  "publishedAt" timestamp(3) without time zone,
  "closedAt" timestamp(3) without time zone,
  "completedAt" timestamp(3) without time zone,
  "cancelledAt" timestamp(3) without time zone,
  "cancellationReason" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  "initiative_id" integer,
  CONSTRAINT "pk_VolunteerOpportunity" PRIMARY KEY ("id")
);

CREATE TABLE public."VolunteerSession" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "opportunityId" integer NOT NULL,
  "title" text,
  "description" text,
  "location" text,
  "startAt" timestamp(3) without time zone NOT NULL,
  "endAt" timestamp(3) without time zone NOT NULL,
  "status" "VolunteerSessionStatus" NOT NULL DEFAULT 'SCHEDULED',
  "cancelledAt" timestamp(3) without time zone,
  "cancellationReason" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_VolunteerSession" PRIMARY KEY ("id")
);

CREATE TABLE public."VolunteerApplication" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "opportunityId" integer NOT NULL,
  "personId" integer,
  "submittedFullName" text NOT NULL,
  "submittedIdentificationType" "IdentificationType",
  "submittedIdentification" text,
  "submittedNormalizedIdentification" text,
  "submittedEmail" text,
  "submittedPhone" text,
  "motivation" text,
  "status" "VolunteerApplicationStatus" NOT NULL DEFAULT 'PENDING',
  "requestedAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "reviewedByUserId" integer,
  "reviewedAt" timestamp(3) without time zone,
  "rejectionReason" text,
  "withdrawnAt" timestamp(3) without time zone,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_VolunteerApplication" PRIMARY KEY ("id")
);

CREATE TABLE public."VolunteerParticipation" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "opportunityId" integer NOT NULL,
  "personId" integer NOT NULL,
  "applicationId" integer NOT NULL,
  "status" "VolunteerParticipationStatus" NOT NULL DEFAULT 'CONFIRMED',
  "confirmedAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "completedAt" timestamp(3) without time zone,
  "cancelledAt" timestamp(3) without time zone,
  "cancellationReason" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_VolunteerParticipation" PRIMARY KEY ("id")
);

CREATE TABLE public."VolunteerAttendance" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "participationId" integer NOT NULL,
  "sessionId" integer NOT NULL,
  "status" "VolunteerAttendanceStatus" NOT NULL,
  "checkInAt" timestamp(3) without time zone,
  "checkOutAt" timestamp(3) without time zone,
  "creditedHours" numeric(8,2) NOT NULL DEFAULT 0,
  "notes" text,
  "recordedByUserId" integer NOT NULL,
  "recordedAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_VolunteerAttendance" PRIMARY KEY ("id")
);

CREATE TABLE public."Venture" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "offerDescription" text,
  "businessPhone" text,
  "businessEmail" text,
  "websiteUrl" text,
  "socialUrl" text,
  "locationText" text,
  "status" "VentureStatus" NOT NULL DEFAULT 'ACTIVE',
  "publicationStatus" "VenturePublicationStatus" NOT NULL DEFAULT 'UNPUBLISHED',
  "incorporatedAt" timestamp(3) without time zone NOT NULL,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_Venture" PRIMARY KEY ("id")
);

CREATE TABLE public."VentureAssociation" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "personId" integer NOT NULL,
  "ventureId" integer NOT NULL,
  "startedAt" timestamp(3) without time zone NOT NULL,
  "endedAt" timestamp(3) without time zone,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_VentureAssociation" PRIMARY KEY ("id")
);

CREATE TABLE public."VentureRequest" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "purpose" "VentureRequestPurpose" NOT NULL,
  "status" "VentureRequestStatus" NOT NULL DEFAULT 'SUBMITTED',
  "reconciledPersonId" integer,
  "ventureId" integer,
  "resolvedAt" timestamp(3) without time zone,
  "decisionReason" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp(3) without time zone NOT NULL,
  CONSTRAINT "pk_VentureRequest" PRIMARY KEY ("id")
);

CREATE TABLE public."VentureRequestRevision" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "requestId" integer NOT NULL,
  "revisionNumber" integer NOT NULL,
  "payloadVersion" integer NOT NULL,
  "submittedData" jsonb NOT NULL,
  "submittedAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_VentureRequestRevision" PRIMARY KEY ("id")
);

CREATE TABLE public."board_session" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "term_id" integer NOT NULL,
  "session_number" integer NOT NULL,
  "scheduled_at" timestamp(3) without time zone,
  "held_at" timestamp(3) without time zone,
  "status" varchar(32) NOT NULL,
  "notes" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_board_session" PRIMARY KEY ("id")
);

CREATE TABLE public."board_minute" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "board_session_id" integer NOT NULL,
  "document_record_id" integer,
  "legacy_content" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_board_minute" PRIMARY KEY ("id")
);

CREATE TABLE public."board_resolution" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "board_session_id" integer NOT NULL,
  "resolution_number" integer NOT NULL,
  "title" text NOT NULL,
  "content" text NOT NULL,
  "resolved_at" timestamp(3) without time zone,
  "document_record_id" integer,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_board_resolution" PRIMARY KEY ("id")
);

CREATE TABLE public."event_revision" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "event_id" integer NOT NULL,
  "revision_number" integer NOT NULL,
  "snapshot" jsonb NOT NULL,
  "submitted_by_user_id" integer,
  "submitted_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_event_revision" PRIMARY KEY ("id")
);

CREATE TABLE public."event_review_decision" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "event_revision_id" integer NOT NULL,
  "membership_id" integer NOT NULL,
  "decided_by_user_id" integer,
  "command_key" varchar(128) COLLATE "C" NOT NULL,
  "result" varchar(32) NOT NULL,
  "reason" text,
  "decided_at" timestamp(3) without time zone NOT NULL,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_event_review_decision" PRIMARY KEY ("id")
);

CREATE TABLE public."event_budget_line" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "event_id" integer NOT NULL,
  "line_number" integer NOT NULL,
  "concept" text NOT NULL,
  "amount" numeric(14,2) NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CRC',
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_event_budget_line" PRIMARY KEY ("id")
);

CREATE TABLE public."in_kind_donation" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "donor_id" integer,
  "recorded_by_user_id" integer,
  "status" varchar(32) NOT NULL,
  "description" text,
  "offered_at" timestamp(3) without time zone,
  "submitted_at" timestamp(3) without time zone,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_in_kind_donation" PRIMARY KEY ("id")
);

CREATE TABLE public."in_kind_donation_item" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "donation_id" integer NOT NULL,
  "line_number" integer NOT NULL,
  "description" text NOT NULL,
  "quantity" numeric(14,3) NOT NULL,
  "unit" varchar(32) NOT NULL,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_in_kind_donation_item" PRIMARY KEY ("id")
);

CREATE TABLE public."in_kind_donation_decision" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "donation_id" integer NOT NULL,
  "membership_id" integer NOT NULL,
  "board_resolution_id" integer,
  "decided_by_user_id" integer,
  "command_key" varchar(128) COLLATE "C" NOT NULL,
  "result" varchar(32) NOT NULL,
  "decided_at" timestamp(3) without time zone NOT NULL,
  "reason" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_in_kind_donation_decision" PRIMARY KEY ("id")
);

CREATE TABLE public."in_kind_donation_receipt" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "donation_id" integer NOT NULL,
  "receipt_number" integer NOT NULL,
  "received_by_user_id" integer NOT NULL,
  "received_at" timestamp(3) without time zone NOT NULL,
  "status" varchar(32) NOT NULL,
  "document_record_id" integer,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_in_kind_donation_receipt" PRIMARY KEY ("id")
);

CREATE TABLE public."in_kind_donation_receipt_line" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "receipt_id" integer NOT NULL,
  "line_number" integer NOT NULL,
  "donation_item_id" integer NOT NULL,
  "item_id" integer NOT NULL,
  "quantity" numeric(14,3) NOT NULL,
  "condition" varchar(32) NOT NULL,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_in_kind_donation_receipt_line" PRIMARY KEY ("id")
);

CREATE TABLE public."institutional_facility" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(200) NOT NULL,
  "description" text,
  "parent_facility_id" integer,
  "status" varchar(32) NOT NULL,
  "location" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_institutional_facility" PRIMARY KEY ("id")
);

CREATE TABLE public."inventory_stock_lot" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "item_id" integer NOT NULL,
  "quantity" numeric(14,3) NOT NULL,
  "condition" varchar(32) NOT NULL,
  "status" varchar(32) NOT NULL,
  "notes" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_inventory_stock_lot" PRIMARY KEY ("id")
);

CREATE TABLE public."inventory_unit" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "asset_code" varchar(64) NOT NULL,
  "item_id" integer NOT NULL,
  "condition" varchar(32) NOT NULL,
  "status" varchar(32) NOT NULL,
  "serial_number" varchar(128),
  "notes" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_inventory_unit" PRIMARY KEY ("id")
);

CREATE TABLE public."maintenance_incident" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "facility_id" integer,
  "stock_lot_id" integer,
  "unit_id" integer,
  "reported_by_person_id" integer,
  "status" varchar(32) NOT NULL,
  "description" text NOT NULL,
  "reported_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_maintenance_incident" PRIMARY KEY ("id")
);

CREATE TABLE public."maintenance_work_order" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "incident_id" integer,
  "facility_id" integer,
  "stock_lot_id" integer,
  "unit_id" integer,
  "executor_person_id" integer,
  "authorized_by_user_id" integer,
  "initiative_id" integer,
  "document_record_id" integer,
  "status" varchar(32) NOT NULL,
  "scope" text,
  "authorized_at" timestamp(3) without time zone,
  "assigned_at" timestamp(3) without time zone,
  "verified_at" timestamp(3) without time zone,
  "closed_at" timestamp(3) without time zone,
  "verification_evidence" jsonb,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_maintenance_work_order" PRIMARY KEY ("id")
);

CREATE TABLE public."resource_unavailability" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reservable_resource_id" integer NOT NULL,
  "incident_id" integer,
  "work_order_id" integer,
  "starts_at" timestamp(3) without time zone NOT NULL,
  "ends_at" timestamp(3) without time zone,
  "released_at" timestamp(3) without time zone,
  "released_by_user_id" integer,
  "reason" text NOT NULL,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_resource_unavailability" PRIMARY KEY ("id")
);

CREATE TABLE public."inventory_loan_checkout_allocation" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "loan_id" integer NOT NULL,
  "lot_id" integer,
  "unit_id" integer,
  "quantity" numeric(14,3) NOT NULL,
  "checkout_movement_id" integer,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "notes" text,
  CONSTRAINT "pk_inventory_loan_checkout_allocation" PRIMARY KEY ("id")
);

CREATE TABLE public."inventory_loan_return" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "loan_id" integer NOT NULL,
  "return_number" integer NOT NULL,
  "received_by_user_id" integer NOT NULL,
  "received_at" timestamp(3) without time zone NOT NULL,
  "status" varchar(32) NOT NULL,
  "notes" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_inventory_loan_return" PRIMARY KEY ("id")
);

CREATE TABLE public."inventory_loan_return_detail" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "return_id" integer NOT NULL,
  "checkout_allocation_id" integer NOT NULL,
  "quantity" numeric(14,3) NOT NULL,
  "condition" varchar(32) NOT NULL,
  "available_entry_movement_id" integer,
  "notes" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_inventory_loan_return_detail" PRIMARY KEY ("id")
);

CREATE TABLE public."inventory_loan_shortage" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_allocation_id" integer NOT NULL,
  "quantity" numeric(14,3) NOT NULL,
  "status" varchar(32) NOT NULL,
  "reason" text,
  "detected_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_inventory_loan_shortage" PRIMARY KEY ("id")
);

CREATE TABLE public."inventory_loan_shortage_decision" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "shortage_id" integer NOT NULL,
  "membership_id" integer NOT NULL,
  "board_resolution_id" integer,
  "decided_by_user_id" integer,
  "command_key" varchar(128) COLLATE "C" NOT NULL,
  "result" varchar(32) NOT NULL,
  "reason" text,
  "decided_at" timestamp(3) without time zone NOT NULL,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_inventory_loan_shortage_decision" PRIMARY KEY ("id")
);

CREATE TABLE public."initiative" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(200) NOT NULL,
  "description" text,
  "status" varchar(32),
  "started_at" date,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_initiative" PRIMARY KEY ("id")
);

CREATE TABLE public."document_record" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "series_id" integer,
  "folio_year" integer,
  "folio_sequence" integer,
  "official_registration_request_key" varchar(128),
  "classification" varchar(16) NOT NULL,
  "status" varchar(32) NOT NULL,
  "official_registered_at" timestamp(3) without time zone,
  "voided_at" timestamp(3) without time zone,
  "void_reason" text,
  "title" varchar(300),
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_document_record" PRIMARY KEY ("id")
);

CREATE TABLE public."document_version" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "document_id" integer NOT NULL,
  "version_number" integer NOT NULL,
  "storage_key" varchar(500) NOT NULL,
  "original_name" varchar(255) NOT NULL,
  "mime_type" varchar(127) NOT NULL,
  "size_bytes" integer NOT NULL,
  "checksum_sha256" char(64) NOT NULL,
  "created_by_user_id" integer,
  "rectifies_version_id" integer,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_document_version" PRIMARY KEY ("id")
);

CREATE TABLE public."document_series" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(200) NOT NULL,
  "description" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "retired_at" timestamp(3) without time zone,
  CONSTRAINT "pk_document_series" PRIMARY KEY ("id")
);

CREATE TABLE public."donor" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "donor_type" varchar(16) NOT NULL,
  "person_id" integer,
  "legal_name" varchar(300),
  "identification_type" varchar(32) NOT NULL,
  "normalized_identification" varchar(128) NOT NULL,
  "display_name" varchar(300) NOT NULL,
  "verified_at" timestamp(3) without time zone,
  "verification_note" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "archived_at" timestamp(3) without time zone,
  CONSTRAINT "pk_donor" PRIMARY KEY ("id")
);

CREATE TABLE public."expense_document_log" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "expense_document_id" integer NOT NULL,
  "actor_user_id" integer,
  "event_type" varchar(32) NOT NULL,
  "event_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "snapshot" jsonb NOT NULL,
  "reason" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_expense_document_log" PRIMARY KEY ("id")
);

CREATE TABLE public."correspondence" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "document_record_id" integer NOT NULL,
  "direction" varchar(16) NOT NULL,
  "counterparty" text NOT NULL,
  "received_or_sent_at" timestamp(3) without time zone,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_correspondence" PRIMARY KEY ("id")
);

CREATE TABLE public."correspondence_log" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "correspondence_id" integer NOT NULL,
  "actor_user_id" integer,
  "event_type" varchar(32) NOT NULL,
  "event_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  "snapshot" jsonb NOT NULL,
  "reason" text,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pk_correspondence_log" PRIMARY KEY ("id")
);

CREATE TABLE public."document_folio_counter" (
  "series_id" integer NOT NULL,
  "folio_year" integer NOT NULL,
  "last_assigned" integer NOT NULL DEFAULT 0,
  CONSTRAINT "pk_document_folio_counter" PRIMARY KEY ("series_id", "folio_year")
);

CREATE TABLE public."inventory_stock_lot_receipt_origin" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lot_id" integer NOT NULL,
  "receipt_line_id" integer NOT NULL,
  CONSTRAINT "pk_inventory_stock_lot_receipt_origin" PRIMARY KEY ("id")
);

CREATE TABLE public."inventory_unit_receipt_origin" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "unit_id" integer NOT NULL,
  "receipt_line_id" integer NOT NULL,
  CONSTRAINT "pk_inventory_unit_receipt_origin" PRIMARY KEY ("id")
);
