-- 76 baseline FKs (B003 replaced by UserRole) + 81 V2 firm FKs.
ALTER TABLE public."RolePermission" ADD CONSTRAINT "fk_RolePermission_roleId" FOREIGN KEY ("roleId") REFERENCES public."Role" ("id") ON DELETE CASCADE ON UPDATE CASCADE; -- B001
ALTER TABLE public."RolePermission" ADD CONSTRAINT "fk_RolePermission_permissionId" FOREIGN KEY ("permissionId") REFERENCES public."Permission" ("id") ON DELETE CASCADE ON UPDATE CASCADE; -- B002
ALTER TABLE public."User" ADD CONSTRAINT "fk_User_personId" FOREIGN KEY ("personId") REFERENCES public."Person" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B004
ALTER TABLE public."Session" ADD CONSTRAINT "fk_Session_userId" FOREIGN KEY ("userId") REFERENCES public."User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B005
ALTER TABLE public."AuditLog" ADD CONSTRAINT "fk_AuditLog_userId" FOREIGN KEY ("userId") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B006
ALTER TABLE public."PasswordResetToken" ADD CONSTRAINT "fk_PasswordResetToken_userId" FOREIGN KEY ("userId") REFERENCES public."User" ("id") ON DELETE CASCADE ON UPDATE CASCADE; -- B007
ALTER TABLE public."AccountActivationToken" ADD CONSTRAINT "fk_AccountActivationToken_userId" FOREIGN KEY ("userId") REFERENCES public."User" ("id") ON DELETE CASCADE ON UPDATE CASCADE; -- B008
ALTER TABLE public."UserRequest" ADD CONSTRAINT "fk_UserRequest_reviewedById" FOREIGN KEY ("reviewedById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B009
ALTER TABLE public."UserRequest" ADD CONSTRAINT "fk_UserRequest_personId" FOREIGN KEY ("personId") REFERENCES public."Person" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B010
ALTER TABLE public."Affiliate" ADD CONSTRAINT "fk_Affiliate_personId" FOREIGN KEY ("personId") REFERENCES public."Person" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B011
ALTER TABLE public."AffiliateRequest" ADD CONSTRAINT "fk_AffiliateRequest_reviewedById" FOREIGN KEY ("reviewedById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B012
ALTER TABLE public."AffiliateRequest" ADD CONSTRAINT "fk_AffiliateRequest_personId" FOREIGN KEY ("personId") REFERENCES public."Person" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B013
ALTER TABLE public."AffiliateSanction" ADD CONSTRAINT "fk_AffiliateSanction_affiliateId" FOREIGN KEY ("affiliateId") REFERENCES public."Affiliate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B014
ALTER TABLE public."AffiliateSanction" ADD CONSTRAINT "fk_AffiliateSanction_createdById" FOREIGN KEY ("createdById") REFERENCES public."User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B015
ALTER TABLE public."BoardAppointment" ADD CONSTRAINT "fk_BoardAppointment_boardTermId" FOREIGN KEY ("boardTermId") REFERENCES public."BoardTerm" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B016
ALTER TABLE public."BoardAppointment" ADD CONSTRAINT "fk_BoardAppointment_positionId" FOREIGN KEY ("positionId") REFERENCES public."GovernancePosition" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B017
ALTER TABLE public."BoardAppointment" ADD CONSTRAINT "fk_BoardAppointment_affiliateId" FOREIGN KEY ("affiliateId") REFERENCES public."Affiliate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B018
ALTER TABLE public."BoardAppointment" ADD CONSTRAINT "fk_BoardAppointment_appointedByAssemblyId" FOREIGN KEY ("appointedByAssemblyId") REFERENCES public."Assembly" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B019
ALTER TABLE public."AssemblyCall" ADD CONSTRAINT "fk_AssemblyCall_assemblyId" FOREIGN KEY ("assemblyId") REFERENCES public."Assembly" ("id") ON DELETE CASCADE ON UPDATE CASCADE; -- B020
ALTER TABLE public."AssemblyConvocation" ADD CONSTRAINT "fk_AssemblyConvocation_assemblyId" FOREIGN KEY ("assemblyId") REFERENCES public."Assembly" ("id") ON DELETE CASCADE ON UPDATE CASCADE; -- B021
ALTER TABLE public."AssemblyConvocation" ADD CONSTRAINT "fk_AssemblyConvocation_affiliateId" FOREIGN KEY ("affiliateId") REFERENCES public."Affiliate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B022
ALTER TABLE public."AssemblyConvocation" ADD CONSTRAINT "fk_AssemblyConvocation_governanceMembershipId" FOREIGN KEY ("governanceMembershipId") REFERENCES public."BoardAppointment" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B023
ALTER TABLE public."AssemblyAttendance" ADD CONSTRAINT "fk_AssemblyAttendance_convocationId" FOREIGN KEY ("convocationId") REFERENCES public."AssemblyConvocation" ("id") ON DELETE CASCADE ON UPDATE CASCADE; -- B024
ALTER TABLE public."AbsenceJustification" ADD CONSTRAINT "fk_AbsenceJustification_attendanceId" FOREIGN KEY ("attendanceId") REFERENCES public."AssemblyAttendance" ("id") ON DELETE CASCADE ON UPDATE CASCADE; -- B025
ALTER TABLE public."AbsenceJustification" ADD CONSTRAINT "fk_AbsenceJustification_reviewedById" FOREIGN KEY ("reviewedById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B026
ALTER TABLE public."AssemblyMinute" ADD CONSTRAINT "fk_AssemblyMinute_assemblyId" FOREIGN KEY ("assemblyId") REFERENCES public."Assembly" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B027
ALTER TABLE public."AssemblyResolution" ADD CONSTRAINT "fk_AssemblyResolution_assemblyId" FOREIGN KEY ("assemblyId") REFERENCES public."Assembly" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B028
ALTER TABLE public."Reservation" ADD CONSTRAINT "fk_Reservation_resourceId" FOREIGN KEY ("resourceId") REFERENCES public."ReservableResource" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B029
ALTER TABLE public."Reservation" ADD CONSTRAINT "fk_Reservation_requesterUserId" FOREIGN KEY ("requesterUserId") REFERENCES public."User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B030
ALTER TABLE public."Reservation" ADD CONSTRAINT "fk_Reservation_approvedById" FOREIGN KEY ("approvedById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B031
ALTER TABLE public."Reservation" ADD CONSTRAINT "fk_Reservation_eventId" FOREIGN KEY ("eventId") REFERENCES public."Event" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B032
ALTER TABLE public."FinancialCharge" ADD CONSTRAINT "fk_FinancialCharge_reservationId" FOREIGN KEY ("reservationId") REFERENCES public."Reservation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B033
ALTER TABLE public."Payment" ADD CONSTRAINT "fk_Payment_chargeId" FOREIGN KEY ("chargeId") REFERENCES public."FinancialCharge" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B034
ALTER TABLE public."Payment" ADD CONSTRAINT "fk_Payment_movementId" FOREIGN KEY ("movementId") REFERENCES public."FinancialMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B035
ALTER TABLE public."Payment" ADD CONSTRAINT "fk_Payment_recordedById" FOREIGN KEY ("recordedById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B036
ALTER TABLE public."FinancialMovement" ADD CONSTRAINT "fk_FinancialMovement_accountId" FOREIGN KEY ("accountId") REFERENCES public."FinancialAccount" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B037
ALTER TABLE public."FinancialMovement" ADD CONSTRAINT "fk_FinancialMovement_recordedById" FOREIGN KEY ("recordedById") REFERENCES public."User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B038
ALTER TABLE public."FinancialMovement" ADD CONSTRAINT "fk_FinancialMovement_voidedById" FOREIGN KEY ("voidedById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B039
ALTER TABLE public."FinancialMovement" ADD CONSTRAINT "fk_FinancialMovement_reversalOfId" FOREIGN KEY ("reversalOfId") REFERENCES public."FinancialMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B040
ALTER TABLE public."Donation" ADD CONSTRAINT "fk_Donation_donorPersonId" FOREIGN KEY ("donorPersonId") REFERENCES public."Person" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B041
ALTER TABLE public."Donation" ADD CONSTRAINT "fk_Donation_recordedById" FOREIGN KEY ("recordedById") REFERENCES public."User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B042
ALTER TABLE public."Donation" ADD CONSTRAINT "fk_Donation_cancelledById" FOREIGN KEY ("cancelledById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B043
ALTER TABLE public."Donation" ADD CONSTRAINT "fk_Donation_originalMovementId" FOREIGN KEY ("originalMovementId") REFERENCES public."FinancialMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B044
ALTER TABLE public."Expense" ADD CONSTRAINT "fk_Expense_authorizationResolutionId" FOREIGN KEY ("authorizationResolutionId") REFERENCES public."AssemblyResolution" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B045
ALTER TABLE public."ExpenseDocument" ADD CONSTRAINT "fk_ExpenseDocument_expenseId" FOREIGN KEY ("expenseId") REFERENCES public."Expense" ("id") ON DELETE CASCADE ON UPDATE CASCADE; -- B046
ALTER TABLE public."Disbursement" ADD CONSTRAINT "fk_Disbursement_expenseId" FOREIGN KEY ("expenseId") REFERENCES public."Expense" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B047
ALTER TABLE public."Disbursement" ADD CONSTRAINT "fk_Disbursement_movementId" FOREIGN KEY ("movementId") REFERENCES public."FinancialMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B048
ALTER TABLE public."FundingAllocation" ADD CONSTRAINT "fk_FundingAllocation_expenseId" FOREIGN KEY ("expenseId") REFERENCES public."Expense" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B049
ALTER TABLE public."FundingAllocation" ADD CONSTRAINT "fk_FundingAllocation_incomeMovementId" FOREIGN KEY ("incomeMovementId") REFERENCES public."FinancialMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B050
ALTER TABLE public."InventoryItem" ADD CONSTRAINT "fk_InventoryItem_categoryId" FOREIGN KEY ("categoryId") REFERENCES public."InventoryCategory" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B051
ALTER TABLE public."InventoryMovement" ADD CONSTRAINT "fk_InventoryMovement_itemId" FOREIGN KEY ("itemId") REFERENCES public."InventoryItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B052
ALTER TABLE public."InventoryMovement" ADD CONSTRAINT "fk_InventoryMovement_createdById" FOREIGN KEY ("createdById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B053
ALTER TABLE public."InventoryLoan" ADD CONSTRAINT "fk_InventoryLoan_itemId" FOREIGN KEY ("itemId") REFERENCES public."InventoryItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B054
ALTER TABLE public."InventoryLoan" ADD CONSTRAINT "fk_InventoryLoan_borrowerAffiliateId" FOREIGN KEY ("borrowerAffiliateId") REFERENCES public."Affiliate" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B055
ALTER TABLE public."InventoryLoan" ADD CONSTRAINT "fk_InventoryLoan_createdById" FOREIGN KEY ("createdById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B056
ALTER TABLE public."InventoryLoan" ADD CONSTRAINT "fk_InventoryLoan_receivedById" FOREIGN KEY ("receivedById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B057
ALTER TABLE public."InventoryLoan" ADD CONSTRAINT "fk_InventoryLoan_cancelledById" FOREIGN KEY ("cancelledById") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B058
ALTER TABLE public."InventoryLoan" ADD CONSTRAINT "fk_InventoryLoan_checkoutMovementId" FOREIGN KEY ("checkoutMovementId") REFERENCES public."InventoryMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B059
ALTER TABLE public."InventoryLoan" ADD CONSTRAINT "fk_InventoryLoan_returnMovementId" FOREIGN KEY ("returnMovementId") REFERENCES public."InventoryMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B060
ALTER TABLE public."InventoryLoan" ADD CONSTRAINT "fk_InventoryLoan_cancellationMovementId" FOREIGN KEY ("cancellationMovementId") REFERENCES public."InventoryMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B061
ALTER TABLE public."VolunteerOpportunity" ADD CONSTRAINT "fk_VolunteerOpportunity_createdByUserId" FOREIGN KEY ("createdByUserId") REFERENCES public."User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B062
ALTER TABLE public."VolunteerSession" ADD CONSTRAINT "fk_VolunteerSession_opportunityId" FOREIGN KEY ("opportunityId") REFERENCES public."VolunteerOpportunity" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B063
ALTER TABLE public."VolunteerApplication" ADD CONSTRAINT "fk_VolunteerApplication_opportunityId" FOREIGN KEY ("opportunityId") REFERENCES public."VolunteerOpportunity" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B064
ALTER TABLE public."VolunteerApplication" ADD CONSTRAINT "fk_VolunteerApplication_personId" FOREIGN KEY ("personId") REFERENCES public."Person" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B065
ALTER TABLE public."VolunteerApplication" ADD CONSTRAINT "fk_VolunteerApplication_reviewedByUserId" FOREIGN KEY ("reviewedByUserId") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B066
ALTER TABLE public."VolunteerParticipation" ADD CONSTRAINT "fk_VolunteerParticipation_opportunityId" FOREIGN KEY ("opportunityId") REFERENCES public."VolunteerOpportunity" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B067
ALTER TABLE public."VolunteerParticipation" ADD CONSTRAINT "fk_VolunteerParticipation_personId" FOREIGN KEY ("personId") REFERENCES public."Person" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B068
ALTER TABLE public."VolunteerParticipation" ADD CONSTRAINT "fk_VolunteerParticipation_applicationId" FOREIGN KEY ("applicationId") REFERENCES public."VolunteerApplication" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B069
ALTER TABLE public."VolunteerAttendance" ADD CONSTRAINT "fk_VolunteerAttendance_participationId" FOREIGN KEY ("participationId") REFERENCES public."VolunteerParticipation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B070
ALTER TABLE public."VolunteerAttendance" ADD CONSTRAINT "fk_VolunteerAttendance_sessionId" FOREIGN KEY ("sessionId") REFERENCES public."VolunteerSession" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B071
ALTER TABLE public."VolunteerAttendance" ADD CONSTRAINT "fk_VolunteerAttendance_recordedByUserId" FOREIGN KEY ("recordedByUserId") REFERENCES public."User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B072
ALTER TABLE public."VentureAssociation" ADD CONSTRAINT "fk_VentureAssociation_personId" FOREIGN KEY ("personId") REFERENCES public."Person" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B073
ALTER TABLE public."VentureAssociation" ADD CONSTRAINT "fk_VentureAssociation_ventureId" FOREIGN KEY ("ventureId") REFERENCES public."Venture" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B074
ALTER TABLE public."VentureRequest" ADD CONSTRAINT "fk_VentureRequest_reconciledPersonId" FOREIGN KEY ("reconciledPersonId") REFERENCES public."Person" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- B075
ALTER TABLE public."VentureRequest" ADD CONSTRAINT "fk_VentureRequest_ventureId" FOREIGN KEY ("ventureId") REFERENCES public."Venture" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B076
ALTER TABLE public."VentureRequestRevision" ADD CONSTRAINT "fk_VentureRequestRevision_requestId" FOREIGN KEY ("requestId") REFERENCES public."VentureRequest" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- B077
ALTER TABLE public."board_session" ADD CONSTRAINT "fk_board_session_term_id" FOREIGN KEY ("term_id") REFERENCES public."BoardTerm" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V001
ALTER TABLE public."board_minute" ADD CONSTRAINT "fk_board_minute_board_session_id" FOREIGN KEY ("board_session_id") REFERENCES public."board_session" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V002
ALTER TABLE public."board_resolution" ADD CONSTRAINT "fk_board_resolution_board_session_id" FOREIGN KEY ("board_session_id") REFERENCES public."board_session" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V003
ALTER TABLE public."event_revision" ADD CONSTRAINT "fk_event_revision_event_id" FOREIGN KEY ("event_id") REFERENCES public."Event" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V006
ALTER TABLE public."event_revision" ADD CONSTRAINT "fk_event_revision_submitted_by_user_id" FOREIGN KEY ("submitted_by_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V007
ALTER TABLE public."event_review_decision" ADD CONSTRAINT "fk_event_review_decision_event_revision_id" FOREIGN KEY ("event_revision_id") REFERENCES public."event_revision" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V008
ALTER TABLE public."event_review_decision" ADD CONSTRAINT "fk_event_review_decision_membership_id" FOREIGN KEY ("membership_id") REFERENCES public."BoardAppointment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V009
ALTER TABLE public."event_review_decision" ADD CONSTRAINT "fk_event_review_decision_decided_by_user_id" FOREIGN KEY ("decided_by_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V010
ALTER TABLE public."event_budget_line" ADD CONSTRAINT "fk_event_budget_line_event_id" FOREIGN KEY ("event_id") REFERENCES public."Event" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V011
ALTER TABLE public."in_kind_donation" ADD CONSTRAINT "fk_in_kind_donation_donor_id" FOREIGN KEY ("donor_id") REFERENCES public."donor" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V012
ALTER TABLE public."in_kind_donation" ADD CONSTRAINT "fk_in_kind_donation_recorded_by_user_id" FOREIGN KEY ("recorded_by_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V013
ALTER TABLE public."in_kind_donation_item" ADD CONSTRAINT "fk_in_kind_donation_item_donation_id" FOREIGN KEY ("donation_id") REFERENCES public."in_kind_donation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V014
ALTER TABLE public."in_kind_donation_decision" ADD CONSTRAINT "fk_in_kind_donation_decision_donation_id" FOREIGN KEY ("donation_id") REFERENCES public."in_kind_donation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V015
ALTER TABLE public."in_kind_donation_decision" ADD CONSTRAINT "fk_in_kind_donation_decision_membership_id" FOREIGN KEY ("membership_id") REFERENCES public."BoardAppointment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V016
ALTER TABLE public."in_kind_donation_decision" ADD CONSTRAINT "fk_in_kind_donation_decision_board_resolution_id" FOREIGN KEY ("board_resolution_id") REFERENCES public."board_resolution" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V017
ALTER TABLE public."in_kind_donation_decision" ADD CONSTRAINT "fk_in_kind_donation_decision_decided_by_user_id" FOREIGN KEY ("decided_by_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V018
ALTER TABLE public."in_kind_donation_receipt" ADD CONSTRAINT "fk_in_kind_donation_receipt_donation_id" FOREIGN KEY ("donation_id") REFERENCES public."in_kind_donation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V019
ALTER TABLE public."in_kind_donation_receipt" ADD CONSTRAINT "fk_in_kind_donation_receipt_received_by_user_id" FOREIGN KEY ("received_by_user_id") REFERENCES public."User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V020
ALTER TABLE public."in_kind_donation_receipt_line" ADD CONSTRAINT "fk_in_kind_donation_receipt_line_receipt_id" FOREIGN KEY ("receipt_id") REFERENCES public."in_kind_donation_receipt" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V021
ALTER TABLE public."in_kind_donation_receipt_line" ADD CONSTRAINT "fk_in_kind_donation_receipt_line_donation_item_id" FOREIGN KEY ("donation_item_id") REFERENCES public."in_kind_donation_item" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V022
ALTER TABLE public."in_kind_donation_receipt_line" ADD CONSTRAINT "fk_in_kind_donation_receipt_line_item_id" FOREIGN KEY ("item_id") REFERENCES public."InventoryItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V023
ALTER TABLE public."institutional_facility" ADD CONSTRAINT "fk_institutional_facility_parent_facility_id" FOREIGN KEY ("parent_facility_id") REFERENCES public."institutional_facility" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V024
ALTER TABLE public."ReservableResource" ADD CONSTRAINT "fk_ReservableResource_facility_id" FOREIGN KEY ("facility_id") REFERENCES public."institutional_facility" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V025
ALTER TABLE public."inventory_stock_lot" ADD CONSTRAINT "fk_inventory_stock_lot_item_id" FOREIGN KEY ("item_id") REFERENCES public."InventoryItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V026
ALTER TABLE public."inventory_stock_lot_receipt_origin" ADD CONSTRAINT "fk_inventory_stock_lot_receipt_origin_lot_id" FOREIGN KEY ("lot_id") REFERENCES public."inventory_stock_lot" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V027
ALTER TABLE public."inventory_stock_lot_receipt_origin" ADD CONSTRAINT "fk_inventory_stock_lot_receipt_origin_receipt_line_id" FOREIGN KEY ("receipt_line_id") REFERENCES public."in_kind_donation_receipt_line" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V028
ALTER TABLE public."inventory_unit" ADD CONSTRAINT "fk_inventory_unit_item_id" FOREIGN KEY ("item_id") REFERENCES public."InventoryItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V029
ALTER TABLE public."inventory_unit_receipt_origin" ADD CONSTRAINT "fk_inventory_unit_receipt_origin_unit_id" FOREIGN KEY ("unit_id") REFERENCES public."inventory_unit" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V030
ALTER TABLE public."inventory_unit_receipt_origin" ADD CONSTRAINT "fk_inventory_unit_receipt_origin_receipt_line_id" FOREIGN KEY ("receipt_line_id") REFERENCES public."in_kind_donation_receipt_line" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V031
ALTER TABLE public."maintenance_incident" ADD CONSTRAINT "fk_maintenance_incident_facility_id" FOREIGN KEY ("facility_id") REFERENCES public."institutional_facility" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V032
ALTER TABLE public."maintenance_incident" ADD CONSTRAINT "fk_maintenance_incident_stock_lot_id" FOREIGN KEY ("stock_lot_id") REFERENCES public."inventory_stock_lot" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V033
ALTER TABLE public."maintenance_incident" ADD CONSTRAINT "fk_maintenance_incident_unit_id" FOREIGN KEY ("unit_id") REFERENCES public."inventory_unit" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V034
ALTER TABLE public."maintenance_incident" ADD CONSTRAINT "fk_maintenance_incident_reported_by_person_id" FOREIGN KEY ("reported_by_person_id") REFERENCES public."Person" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V035
ALTER TABLE public."maintenance_work_order" ADD CONSTRAINT "fk_maintenance_work_order_incident_id" FOREIGN KEY ("incident_id") REFERENCES public."maintenance_incident" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V036
ALTER TABLE public."maintenance_work_order" ADD CONSTRAINT "fk_maintenance_work_order_facility_id" FOREIGN KEY ("facility_id") REFERENCES public."institutional_facility" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V037
ALTER TABLE public."maintenance_work_order" ADD CONSTRAINT "fk_maintenance_work_order_stock_lot_id" FOREIGN KEY ("stock_lot_id") REFERENCES public."inventory_stock_lot" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V038
ALTER TABLE public."maintenance_work_order" ADD CONSTRAINT "fk_maintenance_work_order_unit_id" FOREIGN KEY ("unit_id") REFERENCES public."inventory_unit" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V039
ALTER TABLE public."maintenance_work_order" ADD CONSTRAINT "fk_maintenance_work_order_executor_person_id" FOREIGN KEY ("executor_person_id") REFERENCES public."Person" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V040
ALTER TABLE public."maintenance_work_order" ADD CONSTRAINT "fk_maintenance_work_order_authorized_by_user_id" FOREIGN KEY ("authorized_by_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V041
ALTER TABLE public."Expense" ADD CONSTRAINT "fk_Expense_maintenance_work_order_id" FOREIGN KEY ("maintenance_work_order_id") REFERENCES public."maintenance_work_order" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V042
ALTER TABLE public."Expense" ADD CONSTRAINT "fk_Expense_board_resolution_id" FOREIGN KEY ("board_resolution_id") REFERENCES public."board_resolution" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V043
ALTER TABLE public."Disbursement" ADD CONSTRAINT "fk_Disbursement_settled_by_user_id" FOREIGN KEY ("settled_by_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V044
ALTER TABLE public."resource_unavailability" ADD CONSTRAINT "fk_resource_unavailability_reservable_resource_id" FOREIGN KEY ("reservable_resource_id") REFERENCES public."ReservableResource" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V045
ALTER TABLE public."resource_unavailability" ADD CONSTRAINT "fk_resource_unavailability_incident_id" FOREIGN KEY ("incident_id") REFERENCES public."maintenance_incident" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V046
ALTER TABLE public."resource_unavailability" ADD CONSTRAINT "fk_resource_unavailability_work_order_id" FOREIGN KEY ("work_order_id") REFERENCES public."maintenance_work_order" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V047
ALTER TABLE public."resource_unavailability" ADD CONSTRAINT "fk_resource_unavailability_released_by_user_id" FOREIGN KEY ("released_by_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V048
ALTER TABLE public."inventory_loan_checkout_allocation" ADD CONSTRAINT "fk_inventory_loan_checkout_allocation_loan_id" FOREIGN KEY ("loan_id") REFERENCES public."InventoryLoan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V049
ALTER TABLE public."inventory_loan_checkout_allocation" ADD CONSTRAINT "fk_inventory_loan_checkout_allocation_lot_id" FOREIGN KEY ("lot_id") REFERENCES public."inventory_stock_lot" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V050
ALTER TABLE public."inventory_loan_checkout_allocation" ADD CONSTRAINT "fk_inventory_loan_checkout_allocation_unit_id" FOREIGN KEY ("unit_id") REFERENCES public."inventory_unit" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V051
ALTER TABLE public."inventory_loan_checkout_allocation" ADD CONSTRAINT "fk_inventory_loan_checkout_allocation_checkout_movement_id" FOREIGN KEY ("checkout_movement_id") REFERENCES public."InventoryMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V052
ALTER TABLE public."inventory_loan_return" ADD CONSTRAINT "fk_inventory_loan_return_loan_id" FOREIGN KEY ("loan_id") REFERENCES public."InventoryLoan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V053
ALTER TABLE public."inventory_loan_return" ADD CONSTRAINT "fk_inventory_loan_return_received_by_user_id" FOREIGN KEY ("received_by_user_id") REFERENCES public."User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V054
ALTER TABLE public."inventory_loan_return_detail" ADD CONSTRAINT "fk_inventory_loan_return_detail_return_id" FOREIGN KEY ("return_id") REFERENCES public."inventory_loan_return" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V055
ALTER TABLE public."inventory_loan_return_detail" ADD CONSTRAINT "fk_inventory_loan_return_detail_checkout_allocation_id" FOREIGN KEY ("checkout_allocation_id") REFERENCES public."inventory_loan_checkout_allocation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V056
ALTER TABLE public."inventory_loan_return_detail" ADD CONSTRAINT "fk_inventory_loan_return_detail_available_entry_movement_id" FOREIGN KEY ("available_entry_movement_id") REFERENCES public."InventoryMovement" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V057
ALTER TABLE public."inventory_loan_shortage" ADD CONSTRAINT "fk_inventory_loan_shortage_checkout_allocation_id" FOREIGN KEY ("checkout_allocation_id") REFERENCES public."inventory_loan_checkout_allocation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V058
ALTER TABLE public."inventory_loan_shortage_decision" ADD CONSTRAINT "fk_inventory_loan_shortage_decision_shortage_id" FOREIGN KEY ("shortage_id") REFERENCES public."inventory_loan_shortage" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V059
ALTER TABLE public."inventory_loan_shortage_decision" ADD CONSTRAINT "fk_inventory_loan_shortage_decision_membership_id" FOREIGN KEY ("membership_id") REFERENCES public."BoardAppointment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V060
ALTER TABLE public."inventory_loan_shortage_decision" ADD CONSTRAINT "fk_inventory_loan_shortage_decision_board_resolution_id" FOREIGN KEY ("board_resolution_id") REFERENCES public."board_resolution" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V061
ALTER TABLE public."inventory_loan_shortage_decision" ADD CONSTRAINT "fk_inventory_loan_shortage_decision_decided_by_user_id" FOREIGN KEY ("decided_by_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V062
ALTER TABLE public."Event" ADD CONSTRAINT "fk_Event_initiative_id" FOREIGN KEY ("initiative_id") REFERENCES public."initiative" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V063
ALTER TABLE public."VolunteerOpportunity" ADD CONSTRAINT "fk_VolunteerOpportunity_initiative_id" FOREIGN KEY ("initiative_id") REFERENCES public."initiative" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V064
ALTER TABLE public."maintenance_work_order" ADD CONSTRAINT "fk_maintenance_work_order_initiative_id" FOREIGN KEY ("initiative_id") REFERENCES public."initiative" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V065
ALTER TABLE public."FinancialMovement" ADD CONSTRAINT "fk_FinancialMovement_initiative_id" FOREIGN KEY ("initiative_id") REFERENCES public."initiative" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V066
ALTER TABLE public."document_record" ADD CONSTRAINT "fk_document_record_series_id" FOREIGN KEY ("series_id") REFERENCES public."document_series" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V067
ALTER TABLE public."document_version" ADD CONSTRAINT "fk_document_version_document_id" FOREIGN KEY ("document_id") REFERENCES public."document_record" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V068
ALTER TABLE public."document_version" ADD CONSTRAINT "fk_document_version_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V069
ALTER TABLE public."document_version" ADD CONSTRAINT "fk_document_version_rectifies_version_id" FOREIGN KEY ("rectifies_version_id") REFERENCES public."document_version" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V070
ALTER TABLE public."donor" ADD CONSTRAINT "fk_donor_person_id" FOREIGN KEY ("person_id") REFERENCES public."Person" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V071
ALTER TABLE public."Donation" ADD CONSTRAINT "fk_Donation_donor_id" FOREIGN KEY ("donor_id") REFERENCES public."donor" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V072
ALTER TABLE public."expense_document_log" ADD CONSTRAINT "fk_expense_document_log_expense_document_id" FOREIGN KEY ("expense_document_id") REFERENCES public."ExpenseDocument" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V073
ALTER TABLE public."expense_document_log" ADD CONSTRAINT "fk_expense_document_log_actor_user_id" FOREIGN KEY ("actor_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V074
ALTER TABLE public."correspondence" ADD CONSTRAINT "fk_correspondence_document_record_id" FOREIGN KEY ("document_record_id") REFERENCES public."document_record" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V075
ALTER TABLE public."correspondence_log" ADD CONSTRAINT "fk_correspondence_log_correspondence_id" FOREIGN KEY ("correspondence_id") REFERENCES public."correspondence" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V076
ALTER TABLE public."correspondence_log" ADD CONSTRAINT "fk_correspondence_log_actor_user_id" FOREIGN KEY ("actor_user_id") REFERENCES public."User" ("id") ON DELETE SET NULL ON UPDATE CASCADE; -- V077
ALTER TABLE public."board_minute" ADD CONSTRAINT "fk_board_minute_document_record_id" FOREIGN KEY ("document_record_id") REFERENCES public."document_record" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V078
ALTER TABLE public."board_resolution" ADD CONSTRAINT "fk_board_resolution_document_record_id" FOREIGN KEY ("document_record_id") REFERENCES public."document_record" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V079
ALTER TABLE public."in_kind_donation_receipt" ADD CONSTRAINT "fk_in_kind_donation_receipt_document_record_id" FOREIGN KEY ("document_record_id") REFERENCES public."document_record" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V080
ALTER TABLE public."maintenance_work_order" ADD CONSTRAINT "fk_maintenance_work_order_document_record_id" FOREIGN KEY ("document_record_id") REFERENCES public."document_record" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V081
ALTER TABLE public."ExpenseDocument" ADD CONSTRAINT "fk_ExpenseDocument_document_version_id" FOREIGN KEY ("document_version_id") REFERENCES public."document_version" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V082
ALTER TABLE public."document_folio_counter" ADD CONSTRAINT "fk_document_folio_counter_series_id" FOREIGN KEY ("series_id") REFERENCES public."document_series" ("id") ON DELETE RESTRICT ON UPDATE CASCADE; -- V083
