-- 37 BU total unique indexes + 108 BI firm + 31 VU firm + 58 VI firm.
CREATE UNIQUE INDEX "BU01" ON public."Person" ("identificationType", "normalizedIdentification");
CREATE UNIQUE INDEX "BU02" ON public."Role" ("name");
CREATE UNIQUE INDEX "BU03" ON public."Permission" ("code");
CREATE INDEX "BI001" ON public."RolePermission" ("permissionId");
CREATE UNIQUE INDEX "BU04" ON public."User" ("identification");
CREATE UNIQUE INDEX "BU05" ON public."User" ("email");
CREATE UNIQUE INDEX "BU06" ON public."User" ("personId");
CREATE UNIQUE INDEX "BU07" ON public."Session" ("refreshTokenHash");
CREATE INDEX "BI002" ON public."Session" ("userId");
CREATE INDEX "BI003" ON public."Session" ("expiresAt");
CREATE INDEX "BI004" ON public."AuditLog" ("userId");
CREATE INDEX "BI005" ON public."AuditLog" ("action");
CREATE INDEX "BI006" ON public."AuditLog" ("module");
CREATE INDEX "BI007" ON public."AuditLog" ("createdAt");
CREATE UNIQUE INDEX "BU08" ON public."PasswordResetToken" ("tokenHash");
CREATE INDEX "BI008" ON public."PasswordResetToken" ("userId");
CREATE INDEX "BI009" ON public."PasswordResetToken" ("expiresAt");
CREATE UNIQUE INDEX "BU09" ON public."AccountActivationToken" ("tokenHash");
CREATE INDEX "BI010" ON public."AccountActivationToken" ("userId");
CREATE INDEX "BI011" ON public."AccountActivationToken" ("expiresAt");
CREATE INDEX "BI012" ON public."UserRequest" ("identification");
CREATE INDEX "BI013" ON public."UserRequest" ("email");
CREATE INDEX "BI014" ON public."UserRequest" ("status");
CREATE INDEX "BI015" ON public."UserRequest" ("reviewedById");
CREATE INDEX "BI016" ON public."UserRequest" ("personId");
CREATE UNIQUE INDEX "BU10" ON public."Affiliate" ("identification");
CREATE UNIQUE INDEX "BU11" ON public."Affiliate" ("email");
CREATE UNIQUE INDEX "BU12" ON public."Affiliate" ("personId");
CREATE INDEX "BI017" ON public."Affiliate" ("roleId");
CREATE INDEX "BI018" ON public."AffiliateRequest" ("identification");
CREATE INDEX "BI019" ON public."AffiliateRequest" ("email");
CREATE INDEX "BI020" ON public."AffiliateRequest" ("status");
CREATE INDEX "BI021" ON public."AffiliateRequest" ("reviewedById");
CREATE INDEX "BI022" ON public."AffiliateRequest" ("personId");
CREATE INDEX "BI023" ON public."AffiliateSanction" ("affiliateId");
CREATE INDEX "BI024" ON public."AffiliateSanction" ("status");
CREATE INDEX "BI025" ON public."AffiliateSanction" ("date");
CREATE INDEX "BI026" ON public."AffiliateSanction" ("createdById");
CREATE UNIQUE INDEX "BU13" ON public."GovernancePosition" ("code");
CREATE INDEX "BI027" ON public."BoardTerm" ("institutionalProfileId", "startsOn");
CREATE INDEX "BI028" ON public."BoardAppointment" ("boardTermId");
CREATE INDEX "BI029" ON public."BoardAppointment" ("personId");
CREATE INDEX "BI030" ON public."BoardAppointment" ("position", "seatNumber");
CREATE INDEX "BI031" ON public."BoardAppointment" ("positionId");
CREATE INDEX "BI032" ON public."BoardAppointment" ("affiliateId");
CREATE INDEX "BI033" ON public."BoardAppointment" ("appointedByAssemblyId");
CREATE INDEX "BI034" ON public."Assembly" ("date");
CREATE INDEX "BI035" ON public."Assembly" ("scheduledAt");
CREATE INDEX "BI036" ON public."Assembly" ("status");
CREATE UNIQUE INDEX "BU14" ON public."AssemblyCall" ("assemblyId", "callNumber");
CREATE INDEX "BI037" ON public."AssemblyCall" ("scheduledAt");
CREATE UNIQUE INDEX "BU15" ON public."AssemblyConvocation" ("assemblyId", "affiliateId");
CREATE INDEX "BI039" ON public."AssemblyConvocation" ("affiliateId");
CREATE INDEX "BI040" ON public."AssemblyConvocation" ("roleId");
CREATE INDEX "BI041" ON public."AssemblyConvocation" ("governanceMembershipId");
CREATE UNIQUE INDEX "BU16" ON public."AssemblyAttendance" ("convocationId");
CREATE UNIQUE INDEX "BU17" ON public."AssemblyAttendance" ("assemblyId", "affiliateId");
CREATE INDEX "BI042" ON public."AssemblyAttendance" ("assemblyId", "status");
CREATE INDEX "BI043" ON public."AssemblyAttendance" ("affiliateId");
CREATE UNIQUE INDEX "BU18" ON public."AbsenceJustification" ("attendanceId");
CREATE UNIQUE INDEX "BU19" ON public."AbsenceJustification" ("assemblyId", "affiliateId");
CREATE INDEX "BI044" ON public."AbsenceJustification" ("status");
CREATE INDEX "BI045" ON public."AbsenceJustification" ("reviewedById");
CREATE UNIQUE INDEX "BU20" ON public."AssemblyMinute" ("assemblyId");
CREATE INDEX "BI046" ON public."AssemblyResolution" ("assemblyId");
CREATE UNIQUE INDEX "BU21" ON public."Event" ("publicId");
CREATE INDEX "BI047" ON public."Event" ("publicationStatus", "startAt");
CREATE INDEX "BI048" ON public."Event" ("startAt");
CREATE INDEX "BI049" ON public."ReservableResource" ("status");
CREATE INDEX "BI050" ON public."Reservation" ("requesterUserId");
CREATE INDEX "BI051" ON public."Reservation" ("eventId");
CREATE INDEX "BI052" ON public."Reservation" ("status");
CREATE INDEX "BI053" ON public."Reservation" ("resourceId", "startAt", "endAt");
CREATE UNIQUE INDEX "BU22" ON public."FinancialAccount" ("code");
CREATE UNIQUE INDEX "BU23" ON public."FinancialCharge" ("reservationId");
CREATE INDEX "BI054" ON public."FinancialCharge" ("status");
CREATE INDEX "BI055" ON public."FinancialCharge" ("createdAt");
CREATE UNIQUE INDEX "BU24" ON public."Payment" ("movementId");
CREATE INDEX "BI056" ON public."Payment" ("chargeId");
CREATE INDEX "BI057" ON public."Payment" ("status");
CREATE INDEX "BI058" ON public."Payment" ("recordedById");
CREATE INDEX "BI059" ON public."Payment" ("createdAt");
CREATE UNIQUE INDEX "BU25" ON public."FinancialMovement" ("reversalOfId");
CREATE INDEX "BI060" ON public."FinancialMovement" ("accountId");
CREATE INDEX "BI061" ON public."FinancialMovement" ("occurredAt");
CREATE INDEX "BI062" ON public."FinancialMovement" ("type", "occurredAt");
CREATE INDEX "BI063" ON public."FinancialMovement" ("source", "sourceId");
CREATE INDEX "BI064" ON public."FinancialMovement" ("recordedById");
CREATE INDEX "BI065" ON public."FinancialMovement" ("status", "occurredAt");
CREATE UNIQUE INDEX "BU26" ON public."Donation" ("originalMovementId");
CREATE UNIQUE INDEX "BU27" ON public."Donation" ("reversalMovementId");
CREATE INDEX "BI066" ON public."Donation" ("donorPersonId");
CREATE INDEX "BI067" ON public."Donation" ("status");
CREATE INDEX "BI068" ON public."Donation" ("method");
CREATE INDEX "BI069" ON public."Donation" ("receivedAt");
CREATE INDEX "BI070" ON public."Donation" ("recordedById");
CREATE INDEX "BI071" ON public."Donation" ("cancelledById");
CREATE INDEX "BI072" ON public."Donation" ("status", "receivedAt");
CREATE INDEX "BI073" ON public."Expense" ("authorizationResolutionId");
CREATE INDEX "BI074" ON public."Expense" ("status", "incurredAt");
CREATE INDEX "BI075" ON public."ExpenseDocument" ("expenseId");
CREATE UNIQUE INDEX "BU28" ON public."Disbursement" ("movementId");
CREATE INDEX "BI076" ON public."Disbursement" ("expenseId");
CREATE INDEX "BI077" ON public."FundingAllocation" ("expenseId");
CREATE INDEX "BI078" ON public."FundingAllocation" ("incomeMovementId");
CREATE UNIQUE INDEX "BU29" ON public."InventoryCategory" ("name");
CREATE INDEX "BI079" ON public."InventoryCategory" ("isActive");
CREATE UNIQUE INDEX "BU30" ON public."InventoryItem" ("code");
CREATE INDEX "BI080" ON public."InventoryItem" ("categoryId");
CREATE INDEX "BI081" ON public."InventoryItem" ("status");
CREATE INDEX "BI082" ON public."InventoryItem" ("condition");
CREATE INDEX "BI083" ON public."InventoryMovement" ("itemId");
CREATE INDEX "BI084" ON public."InventoryMovement" ("type");
CREATE INDEX "BI085" ON public."InventoryMovement" ("createdById");
CREATE INDEX "BI086" ON public."InventoryMovement" ("createdAt");
CREATE UNIQUE INDEX "BU31" ON public."InventoryLoan" ("checkoutMovementId");
CREATE UNIQUE INDEX "BU32" ON public."InventoryLoan" ("returnMovementId");
CREATE UNIQUE INDEX "BU33" ON public."InventoryLoan" ("cancellationMovementId");
CREATE INDEX "BI087" ON public."InventoryLoan" ("itemId");
CREATE INDEX "BI088" ON public."InventoryLoan" ("status");
CREATE INDEX "BI089" ON public."InventoryLoan" ("borrowerAffiliateId");
CREATE INDEX "BI090" ON public."InventoryLoan" ("createdById");
CREATE INDEX "BI091" ON public."InventoryLoan" ("cancelledById");
CREATE INDEX "BI092" ON public."InventoryLoan" ("expectedReturnDate");
CREATE INDEX "BI093" ON public."VolunteerOpportunity" ("createdByUserId");
CREATE INDEX "BI094" ON public."VolunteerOpportunity" ("status", "applicationDeadline");
CREATE INDEX "BI095" ON public."VolunteerSession" ("opportunityId", "startAt");
CREATE INDEX "BI096" ON public."VolunteerApplication" ("opportunityId", "status");
CREATE INDEX "BI097" ON public."VolunteerApplication" ("personId", "status");
CREATE INDEX "BI098" ON public."VolunteerApplication" ("submittedNormalizedIdentification");
CREATE INDEX "BI099" ON public."VolunteerApplication" ("reviewedByUserId");
CREATE UNIQUE INDEX "BU34" ON public."VolunteerParticipation" ("applicationId");
CREATE UNIQUE INDEX "BU35" ON public."VolunteerParticipation" ("opportunityId", "personId");
CREATE INDEX "BI100" ON public."VolunteerParticipation" ("personId", "status");
CREATE INDEX "BI101" ON public."VolunteerParticipation" ("opportunityId", "status");
CREATE UNIQUE INDEX "BU36" ON public."VolunteerAttendance" ("participationId", "sessionId");
CREATE INDEX "BI102" ON public."VolunteerAttendance" ("sessionId", "status");
CREATE INDEX "BI103" ON public."VolunteerAttendance" ("recordedByUserId");
CREATE INDEX "BI104" ON public."Venture" ("status", "publicationStatus");
CREATE INDEX "BI105" ON public."VentureAssociation" ("personId");
CREATE INDEX "BI106" ON public."VentureAssociation" ("ventureId");
CREATE INDEX "BI107" ON public."VentureRequest" ("reconciledPersonId");
CREATE INDEX "BI108" ON public."VentureRequest" ("ventureId");
CREATE INDEX "BI109" ON public."VentureRequest" ("status", "createdAt");
CREATE UNIQUE INDEX "BU37" ON public."VentureRequestRevision" ("requestId", "revisionNumber");
CREATE UNIQUE INDEX "uq_membership_active_seat" ON public."BoardAppointment" ("boardTermId", "positionId", "seatNumber") WHERE "endsOn" IS NULL;
CREATE UNIQUE INDEX "uq_volunteer_application_pending" ON public."VolunteerApplication" ("opportunityId", "personId") WHERE status='PENDING' AND "personId" IS NOT NULL;
CREATE UNIQUE INDEX "uq_venture_association_open" ON public."VentureAssociation" ("personId", "ventureId") WHERE "endedAt" IS NULL;
CREATE UNIQUE INDEX "uq_board_session_number" ON public."board_session" ("term_id", "session_number");
CREATE UNIQUE INDEX "uq_board_resolution_number" ON public."board_resolution" ("board_session_id", "resolution_number");
CREATE UNIQUE INDEX "uq_event_revision_number" ON public."event_revision" ("event_id", "revision_number");
CREATE UNIQUE INDEX "uq_event_decision_command" ON public."event_review_decision" ("command_key");
CREATE UNIQUE INDEX "uq_event_budget_line" ON public."event_budget_line" ("event_id", "line_number");
CREATE UNIQUE INDEX "uq_inkind_item_line" ON public."in_kind_donation_item" ("donation_id", "line_number");
CREATE UNIQUE INDEX "uq_inkind_decision_command" ON public."in_kind_donation_decision" ("command_key");
CREATE UNIQUE INDEX "uq_inkind_receipt_number" ON public."in_kind_donation_receipt" ("donation_id", "receipt_number");
CREATE UNIQUE INDEX "uq_inkind_receipt_line" ON public."in_kind_donation_receipt_line" ("receipt_id", "line_number");
CREATE UNIQUE INDEX "uq_facility_code" ON public."institutional_facility" ("code");
CREATE UNIQUE INDEX "uq_stock_lot_code" ON public."inventory_stock_lot" ("code");
CREATE UNIQUE INDEX "uq_inventory_unit_asset_code" ON public."inventory_unit" ("asset_code");
CREATE UNIQUE INDEX "uq_checkout_movement" ON public."inventory_loan_checkout_allocation" ("checkout_movement_id");
CREATE UNIQUE INDEX "uq_loan_return_number" ON public."inventory_loan_return" ("loan_id", "return_number");
CREATE UNIQUE INDEX "uq_return_detail_allocation" ON public."inventory_loan_return_detail" ("return_id", "checkout_allocation_id");
CREATE UNIQUE INDEX "uq_return_detail_movement" ON public."inventory_loan_return_detail" ("available_entry_movement_id");
CREATE UNIQUE INDEX "uq_shortage_decision_command" ON public."inventory_loan_shortage_decision" ("command_key");
CREATE UNIQUE INDEX "uq_initiative_code" ON public."initiative" ("code");
CREATE UNIQUE INDEX "uq_document_series_code" ON public."document_series" ("code");
CREATE UNIQUE INDEX "uq_document_folio" ON public."document_record" ("series_id", "folio_year", "folio_sequence");
CREATE UNIQUE INDEX "uq_document_registration_request" ON public."document_record" ("official_registration_request_key");
CREATE UNIQUE INDEX "uq_document_version_number" ON public."document_version" ("document_id", "version_number");
CREATE UNIQUE INDEX "uq_donor_person" ON public."donor" ("person_id");
CREATE UNIQUE INDEX "uq_donor_legal_identity" ON public."donor" ("identification_type", "normalized_identification") WHERE donor_type='ORGANIZATION';
CREATE UNIQUE INDEX "uq_correspondence_document" ON public."correspondence" ("document_record_id");
CREATE UNIQUE INDEX "uq_lot_origin_lot" ON public."inventory_stock_lot_receipt_origin" ("lot_id");
CREATE UNIQUE INDEX "uq_unit_origin_unit" ON public."inventory_unit_receipt_origin" ("unit_id");
CREATE UNIQUE INDEX "uq_disbursement_settlement" ON public."Disbursement" ("expenseId") WHERE purpose='SETTLEMENT';

-- 58 firm V2 explicit BTREE indexes
CREATE INDEX "VI001" ON public."board_minute" ("board_session_id");
CREATE INDEX "VI003" ON public."event_revision" ("submitted_by_user_id");
CREATE INDEX "VI004" ON public."event_review_decision" ("event_revision_id");
CREATE INDEX "VI005" ON public."event_review_decision" ("membership_id");
CREATE INDEX "VI006" ON public."event_review_decision" ("decided_by_user_id");
CREATE INDEX "VI007" ON public."in_kind_donation" ("donor_id");
CREATE INDEX "VI008" ON public."in_kind_donation" ("recorded_by_user_id");
CREATE INDEX "VI009" ON public."in_kind_donation_decision" ("donation_id");
CREATE INDEX "VI010" ON public."in_kind_donation_decision" ("membership_id");
CREATE INDEX "VI011" ON public."in_kind_donation_decision" ("board_resolution_id");
CREATE INDEX "VI012" ON public."in_kind_donation_decision" ("decided_by_user_id");
CREATE INDEX "VI013" ON public."in_kind_donation_receipt" ("received_by_user_id");
CREATE INDEX "VI014" ON public."in_kind_donation_receipt_line" ("donation_item_id");
CREATE INDEX "VI015" ON public."in_kind_donation_receipt_line" ("item_id");
CREATE INDEX "VI016" ON public."institutional_facility" ("parent_facility_id");
CREATE INDEX "VI017" ON public."inventory_stock_lot" ("item_id");
CREATE INDEX "VI018" ON public."inventory_unit" ("item_id");
CREATE INDEX "VI019" ON public."maintenance_incident" ("facility_id");
CREATE INDEX "VI020" ON public."maintenance_incident" ("stock_lot_id");
CREATE INDEX "VI021" ON public."maintenance_incident" ("unit_id");
CREATE INDEX "VI022" ON public."maintenance_incident" ("reported_by_person_id");
CREATE INDEX "VI023" ON public."maintenance_work_order" ("incident_id");
CREATE INDEX "VI024" ON public."maintenance_work_order" ("facility_id");
CREATE INDEX "VI025" ON public."maintenance_work_order" ("stock_lot_id");
CREATE INDEX "VI026" ON public."maintenance_work_order" ("unit_id");
CREATE INDEX "VI027" ON public."maintenance_work_order" ("executor_person_id");
CREATE INDEX "VI028" ON public."maintenance_work_order" ("authorized_by_user_id");
CREATE INDEX "VI029" ON public."maintenance_work_order" ("initiative_id");
CREATE INDEX "VI030" ON public."resource_unavailability" ("incident_id");
CREATE INDEX "VI031" ON public."resource_unavailability" ("work_order_id");
CREATE INDEX "VI032" ON public."resource_unavailability" ("released_by_user_id");
CREATE INDEX "VI033" ON public."inventory_loan_checkout_allocation" ("loan_id");
CREATE INDEX "VI034" ON public."inventory_loan_checkout_allocation" ("lot_id");
CREATE INDEX "VI035" ON public."inventory_loan_checkout_allocation" ("unit_id");
CREATE INDEX "VI036" ON public."inventory_loan_return" ("received_by_user_id");
CREATE INDEX "VI037" ON public."inventory_loan_return_detail" ("checkout_allocation_id");
CREATE INDEX "VI038" ON public."inventory_loan_shortage" ("checkout_allocation_id");
CREATE INDEX "VI039" ON public."inventory_loan_shortage_decision" ("shortage_id");
CREATE INDEX "VI040" ON public."inventory_loan_shortage_decision" ("membership_id");
CREATE INDEX "VI041" ON public."inventory_loan_shortage_decision" ("board_resolution_id");
CREATE INDEX "VI042" ON public."inventory_loan_shortage_decision" ("decided_by_user_id");
CREATE INDEX "VI043" ON public."Event" ("initiative_id");
CREATE INDEX "VI044" ON public."VolunteerOpportunity" ("initiative_id");
CREATE INDEX "VI045" ON public."FinancialMovement" ("initiative_id");
CREATE INDEX "VI046" ON public."document_version" ("created_by_user_id");
CREATE INDEX "VI047" ON public."document_version" ("rectifies_version_id");
CREATE INDEX "VI048" ON public."Donation" ("donor_id");
CREATE INDEX "VI049" ON public."expense_document_log" ("expense_document_id");
CREATE INDEX "VI050" ON public."expense_document_log" ("actor_user_id");
CREATE INDEX "VI051" ON public."correspondence_log" ("correspondence_id");
CREATE INDEX "VI052" ON public."correspondence_log" ("actor_user_id");
CREATE INDEX "VI053" ON public."ExpenseDocument" ("document_version_id");
CREATE INDEX "VI054" ON public."inventory_stock_lot_receipt_origin" ("receipt_line_id");
CREATE INDEX "VI055" ON public."inventory_unit_receipt_origin" ("receipt_line_id");
CREATE INDEX "VI056" ON public."Expense" ("maintenance_work_order_id");
CREATE INDEX "VI057" ON public."Expense" ("board_resolution_id");
CREATE INDEX "VI058" ON public."Disbursement" ("settled_by_user_id");
CREATE INDEX "VI059" ON public."ReservableResource" ("facility_id");
