-- Consolidation integrated in clean initial migration (not a legacy UPDATE migration).

CREATE TABLE IF NOT EXISTS public."UserRole" (
 "userId" integer NOT NULL REFERENCES public."User"("id") ON DELETE CASCADE,
 "roleId" integer NOT NULL REFERENCES public."Role"("id") ON DELETE RESTRICT,
 CONSTRAINT "pk_UserRole" PRIMARY KEY ("userId", "roleId")
);
CREATE INDEX IF NOT EXISTS "ix_UserRole_roleId" ON public."UserRole"("roleId");

CREATE TABLE IF NOT EXISTS public."VentureManagerAuthorization" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "ventureId" integer NOT NULL REFERENCES public."Venture"("id"),
 "personId" integer NOT NULL REFERENCES public."Person"("id"),
 "grantedByUserId" integer NOT NULL REFERENCES public."User"("id"),
 "grantedByMembershipId" integer NOT NULL REFERENCES public."BoardAppointment"("id"),
 "grantReason" text NOT NULL,
 "validFrom" timestamptz NOT NULL DEFAULT now(),
 "validUntil" timestamptz,
 "revokedAt" timestamptz,
 "revokedByUserId" integer REFERENCES public."User"("id"),
 "revocationReason" text,
 "createdAt" timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT "ck_vma_validity" CHECK ("validUntil" IS NULL OR "validUntil" > "validFrom"),
 CONSTRAINT "ck_vma_revocation" CHECK (("revokedAt" IS NULL AND "revokedByUserId" IS NULL AND "revocationReason" IS NULL) OR ("revokedAt" IS NOT NULL AND "revokedByUserId" IS NOT NULL AND nullif(btrim("revocationReason"),'') IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_vma_unrevoked" ON public."VentureManagerAuthorization"("ventureId","personId") WHERE "revokedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "ix_vma_person" ON public."VentureManagerAuthorization"("personId");

CREATE TABLE IF NOT EXISTS public."VentureReviewerAuthorization" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "userId" integer NOT NULL REFERENCES public."User"("id"),
 "membershipId" integer NOT NULL REFERENCES public."BoardAppointment"("id"),
 "grantedByUserId" integer NOT NULL REFERENCES public."User"("id"),
 "grantReason" text NOT NULL,
 "validFrom" timestamptz NOT NULL DEFAULT now(),
 "validUntil" timestamptz,
 "revokedAt" timestamptz,
 "revokedByUserId" integer REFERENCES public."User"("id"),
 "revocationReason" text,
 "createdAt" timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT "ck_vra_validity" CHECK ("validUntil" IS NULL OR "validUntil" > "validFrom"),
 CONSTRAINT "ck_vra_revocation" CHECK (("revokedAt" IS NULL AND "revokedByUserId" IS NULL AND "revocationReason" IS NULL) OR ("revokedAt" IS NOT NULL AND "revokedByUserId" IS NOT NULL AND nullif(btrim("revocationReason"),'') IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_vra_unrevoked" ON public."VentureReviewerAuthorization"("userId") WHERE "revokedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "ix_vra_membership" ON public."VentureReviewerAuthorization"("membershipId");

CREATE TABLE IF NOT EXISTS public."VentureReviewDecision" (
 "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "ventureId" integer NOT NULL REFERENCES public."Venture"("id"),
 "revisionId" integer REFERENCES public."VentureRequestRevision"("id"),
 "reviewerUserId" integer NOT NULL REFERENCES public."User"("id"),
 "reviewerMembershipId" integer NOT NULL REFERENCES public."BoardAppointment"("id"),
 "reviewerAuthorizationId" integer NOT NULL REFERENCES public."VentureReviewerAuthorization"("id"),
 "decision" text NOT NULL CHECK ("decision" IN ('APPROVE','REJECT','CHANGES_REQUESTED','REVOKE','SUSPEND','CLOSE','RESTORE')),
 "reason" text NOT NULL CHECK (length(btrim("reason")) > 0),
 "decidedAt" timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT "ck_vrd_revision" CHECK (("decision" IN ('APPROVE','REJECT','CHANGES_REQUESTED') AND "revisionId" IS NOT NULL) OR ("decision" IN ('REVOKE','SUSPEND','CLOSE','RESTORE')))
);
CREATE INDEX IF NOT EXISTS "ix_vrd_revision_time" ON public."VentureReviewDecision"("revisionId","decidedAt" DESC);
CREATE INDEX IF NOT EXISTS "ix_vrd_venture_time" ON public."VentureReviewDecision"("ventureId","decidedAt" DESC);

ALTER TABLE public."Venture" ADD COLUMN IF NOT EXISTS "publishedRequestRevisionId" integer;
-- FK en dos fases para conservar compatibilidad con el DDL base.
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_venture_published_revision') THEN
  ALTER TABLE public."Venture" ADD CONSTRAINT "fk_venture_published_revision" FOREIGN KEY ("publishedRequestRevisionId") REFERENCES public."VentureRequestRevision"("id") ON DELETE RESTRICT;
 END IF;
END $$;
CREATE INDEX IF NOT EXISTS "ix_venture_published_revision" ON public."Venture"("publishedRequestRevisionId");
